apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepo-deploy
  namespace: k8s-deeplearning
spec:
  selector:
    matchLabels:
      app: deepo-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: deepo-deploy
    spec:
      volumes:
       - name: cm-apt
         configMap:
           name: cm-deepo
           items:
           - key: sourcelist
             path: sourcelistpath
           - key: jupyterconfig
             path: jupyterconfigpath
       - name: volume-deepo-deploy
         hostPath:
           path: /mnt/disk3/k8s-deepo-workdir
      containers:
        - name: deepo-deploy
          image: ufoym/deepo:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "4000m"
              memory: "8Gi"
            requests:
              cpu: "2000m"
              memory: "4Gi"
          workingDir: /home
          command: ["/bin/bash","-c"]
          args: ["chmod 777 /tmp;pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple;apt update && apt install -y openssh-server;echo PermitRootLogin  yes >>/etc/ssh/sshd_config ;echo 'root:admin' | chpasswd;useradd -m -s /bin/bash cy;echo 'cy:cy'|chpasswd;/etc/init.d/ssh start; pip install jupyterhub;pip install --upgrade notebook;apt install -y npm nodejs-legacy;npm config set registry http://registry.npm.taobao.org;npm install -g configurable-http-proxy;useradd -m -s /bin/bash ljh;echo 'ljh:ljh'|chpasswd;chown -R cy:cy /home/cy;chown -R ljh:ljh /home/ljh;useradd -m -s /bin/bash zl;echo 'zl:zl'|chpasswd;chown -R zl:zl zl;useradd -m -s /bin/bash lyc;echo 'lyc:lyc'|chpasswd;chown -R lyc:lyc lyc;jupyterhub --config=/home/jupyterhub_config.py --no-ssl"]
          ports:
           - name: ssh
             containerPort: 22
             protocol: TCP
           - name: jupyterhub
             containerPort: 8000
          volumeMounts:
           - name: cm-apt
             mountPath: /etc/apt/sources.list
             subPath: sourcelistpath
           - name: cm-apt
             mountPath: /home/jupyterhub_config.py
             subPath: jupyterconfigpath
           - name: volume-deepo-deploy
             mountPath: /home
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 10
      restartPolicy: Always
