# ==================================================================
# module list
# ------------------------------------------------------------------
# python        3.6    (apt)
# jupyter       latest (pip)
# tensorflow    latest (pip)
# jupyterhub    latest (pip)
# jupyterlab    latest (pip)
# keras         latest (pip)
# ssh           (apt)
# ==================================================================
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
ENV LANG C.UTF-8
RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list && \
    rm -rf /var/lib/apt/lists/* \
           /etc/apt/sources.list.d/cuda.list \
           /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-get update
# ==================================================================
# tools
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        apt-utils \
        ca-certificates \
        git \
        vim \
        libssl-dev \
        curl \
        unzip \
        unrar \
        openssh-server \
        && \
    echo PermitRootLogin  yes >>/etc/ssh/sshd_config && \
    echo 'root:admin' | chpasswd
# ==================================================================
# python
# ------------------------------------------------------------------
RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        software-properties-common \
        && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        python3.6 \
        python3.6-dev \
        python3-distutils-extra
ADD package/get-pip.py /root/
RUN PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    python3.6 ~/get-pip.py && \
    ln -s /usr/bin/python3.6 /usr/local/bin/python3 && \
    ln -s /usr/bin/python3.6 /usr/local/bin/python && \
    pip config set global.index-url https://pypi.doubanio.com/simple && \
    $PIP_INSTALL \
        setuptools \
        && \
    $PIP_INSTALL \
        numpy \
        scipy \
        pandas \
        cloudpickle \
        scikit-image>=0.14.2 \
        scikit-learn \
        matplotlib \
        Cython \
        tqdm 
# ==================================================================
# jupyter
# ------------------------------------------------------------------
RUN PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
        jupyter
# ==================================================================
# tensorflow
# ------------------------------------------------------------------
RUN pip install tensorflow-gpu -i https://pypi.doubanio.com/simple
# ==================================================================
# jupyterlab keras jupyterhub  notebook
# ------------------------------------------------------------------
RUN PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    $PIP_INSTALL \
	jupyterhub \
	notebook \
        jupyterlab \
        && \
    $PIP_INSTALL \
        h5py \
	keras
# ==================================================================
# npm config  & cleanup
# ------------------------------------------------------------------
RUN apt-get update && \
    apt install -y npm nodejs && \
    npm config set registry http://registry.npm.taobao.org  && \
    npm install -g configurable-http-proxy && \
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*
EXPOSE 8000 22
