apiVersion: v1
kind: Service
metadata:
  name: k8s-deepo-service
  namespace: k8s-deeplearning
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30033
    name: ssh
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30099
    name: jupyterhub
  selector:
    app: k8s-deepo-deploy
