apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-deepo-cm
  namespace: k8s-deeplearning
data:
  jupyterconfig: |
    c.JupyterHub.proxy_cmd = ['/usr/local/bin/configurable-http-proxy',]
    c.Authenticator.allowed_users = {'ljh','zl','cy','yj','jcz','zx','wf','cmx','lyc'}
    c.Authenticator.delete_invalid_users = True
    c.Authenticator.admin_users = {'ljh'}
    c.Spawner.default_url = '/lab'
    c.LocalAuthenticator.create_system_users = True
    c.NotebookApps.shutdown_no_activity_timeout = 3600
