apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-k8s-deepo.fullname" . }}
  labels:
    {{- include "helm-k8s-deepo.labels" . | nindent 4 }}
spec:
        #sessionAffinity: {{ .Values.service.sessionAffinity }}
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "helm-k8s-deepo.selectorLabels" . | nindent 4 }}
